apiVersion: apps/v1
kind: Deployment
metadata:
  name: library
  namespace: test
  labels:
    app: library
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: library
  template:
    metadata:
      labels:
        app: library
    spec:
      restartPolicy: Always
      containers:
        - name: library
          image: docker.io/adrian2606/library:v4
          resources:
            requests:
              cpu: "100m"
          imagePullPolicy: IfNotPresent #Always
          ports:
            - containerPort: 8881
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/test
            - name: SERVER_PORT
              value: "8881"
            - name: SPRING_FLYWAY_VALIDATE-ON-MIGRATE
              value: "false"
