apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: test
  labels:
    app: library
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      restartPolicy: Always
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_DATABASE
              value: test
            - name: MYSQL_ROOT_PASSWORD
              value: pass
          ports:
            - containerPort: 3306