---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: library
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/adrianrevilla009/continuousDeliveryFluxAndFlagger

